# Site settings
title: The Bees' Knees Berlin
tag_text: 
description: The Bees' Knees Berlin are a barbershop quartet based in Berlin.
# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
