# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            The Bees' Knees
tagline:          'Barbershop in Berlin'
description:      "A women's barbershop quartet based in Berlin."
url:              http://bees.bumble.blue
baseurl:          /

author:
  name:           'Eileen Wagner'
  url:            https://twitter.com/bumblblu

paginate:         5
plugins:          [jekyll-paginate]

# Custom vars
version:          3.5.1

github:
  repo:           https://www.facebook.com/theBK4Berlin/
